JobSphere initialization
acmbpdc/JobSphere pull request #2
Opened 2024-04-19 18:13 UTC by Sanober494

This repo contains career guides, internship info, interview prep resources and more for undergrad students.

2024-04-19 21:21 UTC, Fir121 requested changes
Overall awesome job, I'm excited to go through all the links but from the ones I saw very cool. Lmk when these small formatting changes are done, I will merge this.

2024-04-19 21:21 UTC, Fir121 commented on docs/index.md
> +  * [LPI Summer Intern Program in Planetary Science](https://www.lpi.usra.edu/lpiintern/application/), for both national and international students.
Recheck the formatting here, when served as a mkdocs site.

2024-04-19 21:21 UTC, Fir121 commented on docs/index.md
> +  * [Max Planck Institute for Gravitational Physics](https://www.aei.mpg.de/student-internships), for all students.
Here too. Adding a new line should fix it

2024-04-19 21:21 UTC, Fir121 commented on docs/index.md
> +**JAPAN**
Newline after this

2024-04-19 21:21 UTC, Fir121 commented on docs/index.md
> +**HONG KONG**
Newline here as well.

2024-04-19 21:21 UTC, Fir121 commented on docs/index.md
> +## 3. Interview Preparation
Recheck this on the deployed version

2024-04-19 21:22 UTC, Fir121 commented on docs/index.md
> +1. [Research Internships](#research-internships)
Recheck these internal links

2024-04-20 09:22 UTC, Sanober494 commented
Fixed internal links and added newline

2024-04-20 09:29 UTC, Fir121 commented on docs/index.md
> +  * [LPI Summer Intern Program in Planetary Science](https://www.lpi.usra.edu/lpiintern/application/), for both national and international students.
Use a newline, by doing this the output looks like:

![image](https://github.com/acmbpdc/JobSphere/assets/62911996/81b2383e-7f3a-4c5a-9c91-c7999cc0ad28)

It does not group with the other bullet points

2024-04-20 09:32 UTC, Fir121 commented
Looks good, still some unresolved though. Check it in the mkdocs site.

_Tried to setup an automatic PR previewer to make this easy but it doesn't seem to work for this repository so you will have to stick with local or with your own GitHub Pages to test it out._

2024-04-21 00:14 UTC, Fir121 commented
Also a note -> Deploy previews have been configured for all ACM open source projects! If you want an automatic preview you will have to make a new PR for the same code (will work for any new PRs from now on).

2024-04-25 21:30 UTC, Fir121 commented
Great work! One last thing, you can remove any extra <br> tags only use those when absolutely necessary, the extra space looks a bit odd in the preview.

2024-04-27 11:15 UTC, Fir121 commented
LGTM :rocket: awesome work

2024-04-27 11:15 UTC, merged